/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.unidad2calculadora;
//import javax.Swing.JOptionPane;


/**
 *
 * @Creador Antonio Holguin
 */
public class Calculadora extends javax.swing.JFrame {
    OperadoresCientificos Ops=new OperadoresCientificos();
    String OperadoresSimbolo="";
    String OperadoresSimboloCientifico="";
    boolean presioneOperación=false;
    boolean presioneOperacionCientifica=false;
    float valorA,valorB;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeros = new javax.swing.JTextField();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiplicación = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDivisión = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();
        BtnTan = new javax.swing.JButton();
        BtnCos = new javax.swing.JButton();
        BtnSen = new javax.swing.JButton();
        BtnInversa = new javax.swing.JButton();
        Potencia = new javax.swing.JButton();
        Logaritmo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(288, 360));

        txtNumeros.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNumeros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumeros.setText("0");
        txtNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerosActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnMultiplicación.setText("*");
        btnMultiplicación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicaciónActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnDivisión.setText("/");
        btnDivisión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisiónActionPerformed(evt);
            }
        });

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnBorrar.setText("C");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnBorrarTodo.setText("CE");
        btnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodoActionPerformed(evt);
            }
        });

        BtnTan.setText("Tan");
        BtnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTanActionPerformed(evt);
            }
        });

        BtnCos.setText("Cos");
        BtnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCosActionPerformed(evt);
            }
        });

        BtnSen.setText("Sen");
        BtnSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSenActionPerformed(evt);
            }
        });

        BtnInversa.setText("-1");
        BtnInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInversaActionPerformed(evt);
            }
        });

        Potencia.setText("p");
        Potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotenciaActionPerformed(evt);
            }
        });

        Logaritmo.setText("Log");
        Logaritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogaritmoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Logaritmo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnMultiplicación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(BtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnInversa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSen, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnDivisión, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTan)
                    .addComponent(BtnCos)
                    .addComponent(BtnSen)
                    .addComponent(BtnInversa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Potencia)
                        .addComponent(Logaritmo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicación, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivisión, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        //txtNumeros.setText("0");
        //txtNumeros.setText(numstxt);
        //numstxt=Ops.revisarNumeros(txtNumeros.getText(), evt.getActionCommand());
        String numstxt="";
        if(presioneOperación)
        {
            valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
            txtNumeros.setText(evt.getActionCommand());
            presioneOperación=false;
        }
        else
        {
            numstxt=Ops.revisarNumeros(txtNumeros.getText(),evt.getActionCommand());
            txtNumeros.setText(Ops.revisarComas(numstxt));
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        String numstxt="";
        if(presioneOperación)
        {
            valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
            txtNumeros.setText(evt.getActionCommand());
            presioneOperación=false;
        }
        else
        {
            numstxt=Ops.revisarNumeros(txtNumeros.getText(),evt.getActionCommand());
            txtNumeros.setText(Ops.revisarComas(numstxt));
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        String numstxt="";
        if(presioneOperación)
        {
            valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
            txtNumeros.setText(evt.getActionCommand());
            presioneOperación=false;
        }
        else
        {
            numstxt=Ops.revisarNumeros(txtNumeros.getText(),evt.getActionCommand());
            txtNumeros.setText(Ops.revisarComas(numstxt));
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        String numstxt="";
        if(presioneOperación)
        {
            valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
            txtNumeros.setText(evt.getActionCommand());
            presioneOperación=false;
        }
        else
        {
            numstxt=Ops.revisarNumeros(txtNumeros.getText(),evt.getActionCommand());
            txtNumeros.setText(Ops.revisarComas(numstxt));
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        String numstxt="";
        if(presioneOperación)
        {
            valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
            txtNumeros.setText(evt.getActionCommand());
            presioneOperación=false;
        }
        else
        {
            numstxt=Ops.revisarNumeros(txtNumeros.getText(),evt.getActionCommand());
            txtNumeros.setText(Ops.revisarComas(numstxt));
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        String numstxt="";
        if(presioneOperación)
        {
            valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
            txtNumeros.setText(evt.getActionCommand());
            presioneOperación=false;
        }
        else
        {
            numstxt=Ops.revisarNumeros(txtNumeros.getText(),evt.getActionCommand());
            txtNumeros.setText(Ops.revisarComas(numstxt));
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        String numstxt="";
        if(presioneOperación)
        {
            valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
            txtNumeros.setText(evt.getActionCommand());
            presioneOperación=false;
        }
        else
        {
            numstxt=Ops.revisarNumeros(txtNumeros.getText(),evt.getActionCommand());
            txtNumeros.setText(Ops.revisarComas(numstxt));
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        String numstxt="";
        if(presioneOperación)
        {
            valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
            txtNumeros.setText(evt.getActionCommand());
            presioneOperación=false;
        }
        else
        {
            numstxt=Ops.revisarNumeros(txtNumeros.getText(),evt.getActionCommand());
            txtNumeros.setText(Ops.revisarComas(numstxt));
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        String numstxt="";
        if(presioneOperación)
        {
            valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
            txtNumeros.setText(evt.getActionCommand());
            presioneOperación=false;
        }
       
        else
        {
            numstxt=Ops.revisarNumeros(txtNumeros.getText(),evt.getActionCommand());
            txtNumeros.setText(Ops.revisarComas(numstxt));
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        String numstxt="";
        if(presioneOperación)
        {
            valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
            txtNumeros.setText(evt.getActionCommand());
            presioneOperación=false;
        }
        else
        {
            numstxt=Ops.revisarNumeros(txtNumeros.getText(),evt.getActionCommand());
            txtNumeros.setText(Ops.revisarComas(numstxt));
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        txtNumeros.setText(Ops.revisarComas(Ops.BorrarCaracter(txtNumeros.getText())));
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        // TODO add your handling code here:
        txtNumeros.setText("0");
    }//GEN-LAST:event_btnBorrarTodoActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
        txtNumeros.setText(Ops.revisarPunto(txtNumeros.getText()));
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:
        presioneOperación=true;
        OperadoresSimbolo=evt.getActionCommand();
        valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
        presioneOperación=true;
        OperadoresSimbolo=evt.getActionCommand();
        valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnMultiplicaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicaciónActionPerformed
        // TODO add your handling code here:
        presioneOperación=true;
        OperadoresSimbolo=evt.getActionCommand();
        valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
    }//GEN-LAST:event_btnMultiplicaciónActionPerformed

    private void btnDivisiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisiónActionPerformed
        // TODO add your handling code here:
        presioneOperación=true;
        OperadoresSimbolo=evt.getActionCommand();
        valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
    }//GEN-LAST:event_btnDivisiónActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // TODO add your handling code here:
        //txtNumeros.setText(Float.toString(resultadoTxt));
        float resultadoTxt=0;
        valorB=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
        if(presioneOperacionCientifica==true)
        {
            resultadoTxt=Ops.realizarOperacionCientifica(valorA, valorB, OperadoresSimbolo);
            presioneOperacionCientifica=false;
        }
        else
        {
            resultadoTxt=Ops.realizarOperacion(valorA, valorB, OperadoresSimbolo);
        }
      
        
        txtNumeros.setText(Ops.revisarComas(Float.toString(resultadoTxt)));
    }//GEN-LAST:event_btnIgualActionPerformed

    private void txtNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerosActionPerformed

    private void BtnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTanActionPerformed
        // TODO add your handling code here:
        presioneOperación=true;
        presioneOperacionCientifica=true;
        OperadoresSimbolo=evt.getActionCommand();
        valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
    }//GEN-LAST:event_BtnTanActionPerformed

    private void BtnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCosActionPerformed
        // TODO add your handling code here:
        presioneOperación=true;
        presioneOperacionCientifica=true;
        OperadoresSimbolo=evt.getActionCommand();
        valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText())); 
    }//GEN-LAST:event_BtnCosActionPerformed

    private void BtnSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSenActionPerformed
        // TODO add your handling code here:
        presioneOperación=true;
        presioneOperacionCientifica=true;
        OperadoresSimbolo=evt.getActionCommand();
        valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
    }//GEN-LAST:event_BtnSenActionPerformed

    private void PotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotenciaActionPerformed
        presioneOperación=true;
        presioneOperacionCientifica=true;
        OperadoresSimbolo=evt.getActionCommand();
        valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText())); // TODO add your handling code here:
    }//GEN-LAST:event_PotenciaActionPerformed

    private void LogaritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogaritmoActionPerformed
        presioneOperación=true;
        presioneOperacionCientifica=true;
        OperadoresSimbolo=evt.getActionCommand();// TODO add your handling code here:
        valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
    }//GEN-LAST:event_LogaritmoActionPerformed

    private void BtnInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInversaActionPerformed
        presioneOperación=true;
        presioneOperacionCientifica=true;
        OperadoresSimbolo=evt.getActionCommand();// TODO add your handling code here:
        valorA=Float.parseFloat(Ops.quitarComas(txtNumeros.getText()));
    }//GEN-LAST:event_BtnInversaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calculadora().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCos;
    private javax.swing.JButton BtnInversa;
    private javax.swing.JButton BtnSen;
    private javax.swing.JButton BtnTan;
    private javax.swing.JButton Logaritmo;
    private javax.swing.JButton Potencia;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnDivisión;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplicación;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JTextField txtNumeros;
    // End of variables declaration//GEN-END:variables
}
